In [5]:
from theano import function
import theano
import theano.tensor as T
import numpy as np

In [6]:
X=T.matrix('X')
W=T.matrix('W')
b_sym=T.vector('b_sym')

In [7]:
results,updates=theano.scan(lambda v: T.tanh(T.dot(v,W)+b_sym),sequences=X)
compute_elementwise=function([X,W,b_sym],results)

WARNING (theano.tensor.blas): We did not found a dynamic library into the library_dir of the library we use for blas. If you use ATLAS, make sure to compile it with dynamics library.
WARNING (theano.tensor.blas): We did not found a dynamic library into the library_dir of the library we use for blas. If you use ATLAS, make sure to compile it with dynamics library.


In [9]:
x=np.eye(2,dtype=theano.config.floatX)
print x

[[ 1.  0.]
 [ 0.  1.]]


In [10]:
w=np.ones((2,2),dtype=theano.config.floatX)
b=np.ones((2), dtype=theano.config.floatX)

In [11]:
print b

[ 1.  1.]


In [12]:
b[1]=2
print compute_elementwise(x,w,b)

[[ 0.96402758  0.99505475]
 [ 0.96402758  0.99505475]]


In [13]:
T.dot([1,0],w)

dot.0

In [14]:
T.dot(x,w)

dot.0

In [15]:
x

array([[ 1.,  0.],
       [ 0.,  1.]])

In [16]:
w

array([[ 1.,  1.],
       [ 1.,  1.]])

In [18]:
T.dot(x,w)+b

Elemwise{add,no_inplace}.0

In [24]:
np.dot(np.eye(2)[0],np.ones((2,2)))

array([ 1.,  1.])

In [23]:
np.eye(2)[0]

array([ 1.,  0.])

In [22]:
np.ones((2,2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [25]:
print np.tanh(x.dot(w)+b)

[[ 0.96402758  0.99505475]
 [ 0.96402758  0.99505475]]
