In [1]:
import tensorflow as tf

In [5]:
# Example with tf.train.batch dynamic padding

tf.reset_default_graph()

# Create a tensor [0, 1, 2, 3, 4, ...]
x = tf.range(0, 10, name='x')

# A queue that outputs 0, 1, 2, 3, ...
range_q = tf.train.range_input_producer(limit=5, shuffle=False)
slice_end = range_q.dequeue()

# Slice x to variable length, i.e. [0], [0, 1], [0, 1, 2], ..
y = tf.slice(x, [0], [slice_end], name='y')

print(y)


Tensor("y:0", shape=(?,), dtype=int32)


In [8]:
# Batch the variable length tensor with dynamic padding
batched_data = tf.train.batch(
    tensors=[y],
    batch_size=5,
    dynamic_pad=True,
    name='y_batch'
)

print(batched_data)

Tensor("y_batch_2:0", shape=(5, ?), dtype=int32)


In [11]:
# Run the graph
res = tf.contrib.learn.run_n({'y': batched_data}, n=1, feed_dict=None)

# Print the result
print("Batch shape: {}".format(res[0]["y"].shape))
print(res[0]["y"])

Instructions for updating:
graph_actions.py will be deleted. Use tf.train.* utilities instead. You can use learn/estimators/estimator.py as an example.
Instructions for updating:
graph_actions.py will be deleted. Use tf.train.* utilities instead. You can use learn/estimators/estimator.py as an example.
Instructions for updating:
graph_actions.py will be deleted. Use tf.train.* utilities instead. You can use learn/estimators/estimator.py as an example.
Batch shape: (5, 3)
[[0 0 0]
 [0 1 2]
 [0 0 0]
 [0 1 2]
 [0 0 0]]
